import "./globals.css";
import { Bebas_Neue, Montserrat } from "next/font/google";

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--mont",
  subsets: ["latin"],
});
const bebas = Bebas_Neue({
  weight: ["400"],
  variable: "--bebas",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${bebas.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
